services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: sentiment_user
      POSTGRES_PASSWORD: sentiment_pass
      POSTGRES_DB: sentiment_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentiment_user -d sentiment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    image: python:3.12-slim
    working_dir: /mlflow
    command:
      - sh
      - -c
      - |
        pip install --no-cache-dir mlflow==3.14.0 &&\
        mlflow server --backend-store-uri sqlite:///mlflow.db\
          --default-artifact-root /mlflow/mlruns\
          --host 0.0.0.0 --port 5000\
          --allowed-hosts mlflow,mlflow:*,localhost,localhost:*
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow                 # named volume cho DB + artifacts
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 300s

  bootstrap:
    build: .
    command: ["python", "src/bootstrap.py"]
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: sentiment-classifier
      MODEL_ALIAS: champion
    volumes:
      - ./artifacts:/app/artifacts          # mount .pkl files tu host
      - mlflow_data:/mlflow                 # share mlflow artifacts folder
    depends_on:
      mlflow:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://sentiment_user:sentiment_pass@postgres:5432/sentiment_db
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: sentiment-classifier
      MODEL_ALIAS: champion
    volumes:
      - mlflow_data:/mlflow                 # MLflow can write cache/metadata here
    depends_on:
      bootstrap:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy

volumes:
  postgres_data:
  mlflow_data: