import sqlite3
conn = sqlite3.connect("/mlflow/mlflow.db")
cur = conn.cursor()
print("--- logged_models ---")
cur.execute("SELECT model_id, artifact_location FROM logged_models WHERE model_id = ?", ("m-36d9f444430d4b8eb9f7baf74a93a7f4",))
print(cur.fetchall())
print("--- runs ---")
cur.execute("SELECT run_uuid, artifact_uri, experiment_id FROM runs")
print(cur.fetchall())
print("--- experiments ---")
cur.execute("SELECT experiment_id, artifact_location FROM experiments")
print(cur.fetchall())
print("--- model_versions ---")
cur.execute("SELECT name, version, source, run_id FROM model_versions")
print(cur.fetchall())
