[pytest]    #Cấu hình riêng cho pytest
pythonpath = .          #Coi thư mục hiện tại (root) là điểm bắt đầu tìm kiếm module -> pytest biết src\ ở đâu để import
testpaths = tests         #Pytest chỉ chạy file test trong thư mục tests